### PR TITLE
Fix spec references & two examples

### PR DESCRIPTION
**Pull request by decentralgabe**
examples were using `formatMinimum` instead of the specified `minimum`

### CODE REVIEW

**Comment by decentralgabe** [comment]
it appears the tests fail because `minimum` expects a number. I believe this is a problem with the test...

**Comment by JaceHensley** [comment]
`minimum`/`maximum` is only for numbers, https://github.com/ajv-validator/ajv-formats#keywords-to-compare-values-formatmaximum--formatminimum-and-formatexclusivemaximum--formatexclusiveminimum

**Comment by decentralgabe** [comment]
Ok...upon further investigation:

`formatMaximum` and `formatMinimum` are not defined in the Draft 7 specs:
- https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02
- https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-02
- https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-hyperschema-02

There is [a specific JS library](https://www.npmjs.com/package/ajv/v/6.12.5#features) that supports these additional fields...but it's not in the spec. So neither my change, nor the spec are correct and we probably need non-normative language to support non-integer min/max validation.

**Comment by decentralgabe** [comment]
@JaceHensley that library uses a non-normative _json schema extension_ to define these properties...which isn't widely supported across json schema libraries

**Comment by JaceHensley** [comment]
yeah I noticed that this week, I could've sworn I saw `formatMinimum` on https://json-schema.org/ previously but when I went back to look at it again I couldn't find it.

**Comment by csuwildcat** [comment]
What is formatMinimum anyway?

**Comment by JaceHensley** [comment]
It's a `minimum`, but the the comparison is based on the JSON schema `format` (date, date-time, uri, uuid, ip, etc.)

**Comment by decentralgabe** [comment]
thanks @bumblefudge minor fixes - updated!

**Review by csuwildcat — APPROVED** [review]

**Review by JaceHensley — APPROVED** [review]

**Pull request merged**
