### PR TITLE
Rename Presentation Submission to Presentation Manifest

### PR DESCRIPTION
**Pull request by rado0x54**
Note, the naming for `Submission Requirements` was not changed.
The `Credential Manifest` specification will very likely be renamed to so that the confusion around the reuse of `Manifest` stays as small as possible.

### CODE REVIEW

**Review by glcohen — CHANGES_REQUESTED** [review]
IMO Manifest is much more confusing term than submission, especially when it's something you're submitting.

**Comment by rado0x54** [comment]
@glcohen please see discussion in #166. It was a decision made in the PE meeting, so best to challenge it right in the issue.

**Review by brentzundel — APPROVED** [review]

**Review by glcohen — APPROVED** [review]
I don't like it but I understand it and can't think of anything better

**Review by csuwildcat — CHANGES_REQUESTED** [review]
I believe we should keep the current names for the props involved, and instead add text to better describe Presentation Submissions.

**Comment by csuwildcat** [comment]
Decided on last call that we will retain the Presentation Submission terminology, and just need more descriptive text for its definition.

**Pull request closed without merging**
