### PR TITLE
Add allow_self_issued and fix example Presentation Definition

### PR DESCRIPTION
**Pull request by csuwildcat**

### CODE REVIEW

**Comment by brentzundel** [comment]
How is this different from `subject_is_issuer`?

**Comment by csuwildcat** [comment]
Honestly forgot about it, but I think there's still something I'd add a value of "allowed" or "optional" to subject_is_issuer, because the intent here is to signal that the input being described is not preferred or required to be from them, but merely open to it being so.

**Comment by csuwildcat** [comment]
Honestly forgot about it, but I think there's still something I'd add a value of "allowed" or "optional" to subject_is_issuer, because the intent here is to signal that the input being described is not preferred or required to be from them, but merely open to it being so.

**Comment by csuwildcat** [comment]
I'd also update the Note in that section to not be strictly about directing them to self-issue because you say so, but also note that it can be used as a signal that the JSON Schema inputs can be rendered in a form by a wallet for self-input of data. We're planning to do this in our wallet extension.

**Comment by csuwildcat** [comment]
Closing in favor of new subject_is_issuer value PR

**Pull request closed without merging**
