### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by OR13**

### CODE REVIEW

**Review by troyronda — APPROVED** [review]
LGTM

**Comment by OR13** [comment]
I am merging this, since its malformed jsonld.

**Comment by llorllale** [comment]
When is this fix going live?

**Comment by csuwildcat** [comment]
@llorllale  isn't it already? --> https://identity.foundation/presentation-exchange/submission/v1/index.json

**Comment by llorllale** [comment]
@csuwildcat not yet.

Clicking on https://identity.foundation/presentation-exchange/submission/v1 results in the same incorrect context:

```json
{
  "@version": 1.1,
  "PresentationSubmission": {
    "@id": "https://identity.foundation/presentation-exchange/#presentation-submission",
    "@context": {
      "@version": 1.1,
      "presentation_submission": {
        "@id": "https://identity.foundation/presentation-exchange/#presentation-submission",
        "@type": "@json"
      }
    }
  }
}

```

**Comment by llorllale** [comment]
ie. implementations do not work unless they preload the correct JSONLD context

**Pull request merged**
