### PR TITLE
Create profile

### PR DESCRIPTION
**Pull request by David-Chadwick**

### CODE REVIEW

**Comment by David-Chadwick** [comment]
# Appendix n. Simple Conjunctive Presentation Definition Profile for Verifiable Credentials

Editor: David Chadwick, Crossword Cyber Security PLC

Date: 28 December 2021

Version: 0.2



1. **Introduction**

The purpose of this presentation definition (PD) profile of presentation exchange (PE) is to cater for a large number of uses cases whilst significantly simplifying the features and functionality of the PD that wallets and verifiers need to support.

This profile allows the Verifier to ask for any number of W3C Verifiable Credentials, each of which may be selectively disclosed. 

This profile does not cater for credential formats other than the W3C VC format.

This profile recognises that regardless of the proof format of the verifiable credential, nevertheless the credential will always have the same JSON format. This is the format that will always be referred to in the path property of this profile.

2. **Supported Fields**

i. Presentation Definition

- The id property MUST be present as described in PE.
- The input_descriptors object MUST be present. The value of this object is restricted from its definition in PE as described below.
- The name property MAY be present as described in PE.
- The purpose property MAY be present as described in PE.
- The frame property MUST NOT be present.
- The format property MUST NOT be present. 
- The submission_requirements property MUST NOT be present.

ii. Input Descriptor

- The id property MUST be present as described in PE.
- The group property MUST NOT be present.
- The name property MAY be present as described in PE.
- The purpose property MAY be present as described in PE.
- The format property MUST NOT be present.
- The constraints property SHOULD be present. The value of this object is restricted from its definition in PE as described below.

iii. Constraints

- The types property MUST NOT be present.
- The fields property SHOULD be present. The value of this object is restricted from its definition in PE as described below.
- The limit_disclosure property MAY be present. If present its value MUST be preferred.
- The statuses property MUST NOT be present.
- The subject_is_issuer property MUST NOT be present.
- The is_holder property MUST NOT be present.
- The same_subject property MUST NOT be present.

iv. Fields

- The id property MUST NOT be present.
- The path property SHOULD be present. The value of the path property will always take the format “$.<verifiable credential property>” e.g. “$.issuer”, as these are the only type of credential that is supported by this profile. To be clear, JWT claim names and “$.vc.xxxxx” path values will never occur.
- The purpose property MUST NOT be present.
- The filter property MAY be present. If it is absent and limit_disclosure is present, this indicates that the field should be present in the returned verifiable credential, but the field is not being used to filter the credentials that should be returned.
- The predicate property MUST NOT be present.

3. **Unsupported Fields**

All properties that are not mentioned in section 2 above are not supported and must not occur in a PD that conforms to this profile. Below we give the rationale for why some of the unsupported properties have not been included in this profile.

The format property is not included in this profile because Verifiers can publish their supported formats in the same way that they publish their other metadata.

The submission_requirements property is not present because this CNF profile does not cater for alternative requirements. The Verifier specifies the set of VCs that it requires, and each VC is the set must be returned. This restriction removes the need for the group property in the input_descriptor.

The input_descriptor.constraints.types property is omitted because exactly the same functionality can be provided by the fields property that is supported.



4. **Examples**

i. The Verifier wants a specific type of verifiable credential to be returned, regardless of the issuer. No selective disclosure is required.

```
{
  "presentation_definition": {
    "id": "first simple example",
    "input_descriptors": [
      {
        "id": "A specific type of VC",
        "name": "A specific type of VC",
        "purpose": "We want a VC of this type",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "pattern": "<the type of VC e.g. degree certificate>"
              }
            }
          ]
        }
      }
    ]
  }
}
```

ii. The Verifier wants a specific type of verifiable credential from a specific issuer to be returned, with only a subset of its properties (i.e. selective disclosure).

```
{
  "presentation_definition": {
    "id": "Second example with selective disclosure",
    "input_descriptors": [
      {
        "id": "degree certificate",
        "name": "Degree from university X",
        "purpose": "We want to know you are a graduate from our university",
        "constraints": {
          "limit_disclosure": "preferred",
          "fields": [
            {
              "path": [
                "$.issuer"
              ],
              "filter": {
                "type": "string",
                "pattern": "https://universityx.edu"
              }
            },
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "pattern": "University Degree"
              }
            },
            {
              "path": [
                "$.credentialSubject.degree.class"
              ]
            }
          ]
        }
      }
    ]
  }
}
```

iii. The Verifier wants a self-issued verifiable credential of a specific type to be returned. This is achieved by setting the fields.filter property value to “self-issued.me” (taken from OIDC)

```
{
  "presentation_definition": {
    "id": "self-issued example",
    "input_descriptors": [
      {
        "id": "A self-issued VC",
        "name": "A self-issued VC",
        "purpose": "We want a self-issued VC of type X",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.issuer"
              ],
              "filter": {
                "type": "string",
                "pattern": "self-issued.me"
              }
            },
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "pattern": "X"
              }
            }
          ]
        }
      }
    ]
  }
}
```

iv. The Verifier wants a generic type of verifiable credential from an issuer who is a member of a trusted federation. This uses the TRAIN Terms of Use method for specifying trusted federations.

```
{
  "presentation_definition": {
    "id": "Scalable trust example",
    "input_descriptors": [
      {
        "id": "any type of credit card from any bank",
        "name": "any type of credit card from any bank",
        "purpose": "Please provide your credit card details",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.termsOfUse.type"
              ],
              "filter": {
                "type": "string",
                "pattern": "https://train.trust-scheme.de/info"
              }
            },
            {
              "path": [
                "$.termsOfUse.trustScheme"
              ],
              "filter": {
                "type": "string",
                "pattern": "worldbankfederation.com"
              }
            },
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "pattern": "creditCard"
              }
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by OR13** [comment]
> This profile recognises that regardless of the proof format of the verifiable credential, nevertheless the credential will always have the same JSON format. This is the format that will always be referred to in the path property of this profile.

I would argue that this is a requirement for PE to be adopted for VC use cases, and such a profile seems very desperately needed... and would be helpful when negotiating issues with VC Data Model 2.0

**Review by OR13 — APPROVED** [review]

**Comment by tlodderstedt** [comment]
Hi @David-Chadwick,

thanks for preparing this proposal for a simple PE profile. 

I noticed your proposal does not support "format" at all. How do you envision the verifier to tell the holder/wallet which format it expects?

I also notice the verifier won't have the ability to request Credential A or B. I'm wondering whether we really can do without it. 

I assume your proposal does not support "presentation_submission" at all?

best regards.
Torsten.

**Comment by David-Chadwick** [comment]
> Hi @David-Chadwick,
> 
> thanks for preparing this proposal for a simple PE profile.
> 
> I noticed your proposal does not support "format" at all. How do you envision the verifier to tell the holder/wallet which format it expects?

By publishing it in metadata (static) or transferring it in protocol (dynamic)

> 
> I also notice the verifier won't have the ability to request Credential A or B. I'm wondering whether we really can do without it.

The idea is that the base layer will ask for A and B, whilst an optional layer above will refine this to A or B. A "dumb" wallet that does not understand the upper layer will return both (which over-satisfies the verifier) whilst a more intelligent wallet will just return one.

> 
> I assume your proposal does not support "presentation_submission" at all?

This would be another of the optional upper layers.

> 
> best regards. Torsten.

**Comment by kimdhamilton** [comment]
to discuss Feb 10 2022: ok to close?

**Comment by JaceHensley** [comment]
Superseded by https://github.com/decentralized-identity/presentation-exchange/pull/287

**Pull request closed without merging**
